# Generated by Django 4.2.17 on 2025-01-21 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_subject_teacher_student_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='SchoolClass',
        ),
    ]
